name: aae5305
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py310h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - appdirs==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bidict==0.23.1
      - catkin-pkg==1.1.0
      - certifi==2026.1.4
      - cfclient==2025.12.1
      - cflib==0.1.31
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - docutils==0.22.4
      - empy==3.3.4
      - exceptiongroup==1.3.1
      - fastapi==0.133.0
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - h11==0.16.0
      - hsluv==5.0.4
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - ifaddr==0.2.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lark==1.1.1
      - libusb-package==1.0.26.3
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - multidict==6.7.1
      - nicegui==2.20.0
      - numpy==2.2.6
      - orjson==3.11.7
      - pillow==12.1.1
      - propcache==0.4.1
      - pscript==0.7.7
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - pyqt6==6.7.1
      - pyqt6-qt6==6.7.3
      - pyqt6-sip==13.11.0
      - pyqtgraph==0.14.0
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.13.1
      - python-multipart==0.0.22
      - python-socketio==5.16.1
      - pyusb==1.3.1
      - pyyaml==6.0.3
      - pyzmq==26.4.0
      - requests==2.32.5
      - rowan==1.3.2
      - scipy==1.15.3
      - setuptools==82.0.0
      - simple-websocket==1.1.0
      - six==1.17.0
      - starlette==0.52.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.41.0
      - uvloop==0.22.1
      - vbuild==0.8.2
      - vispy==0.15.2
      - watchfiles==1.1.1
      - websockets==16.0
      - wsproto==1.3.2
      - yarl==1.22.0
variables:
  PYTHONNOUSERSITE: '1'
prefix: /home/aaet/miniconda3/envs/aae5305
